// <auto-generated />
using System;
using JazFinanzasApp.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JazFinanzasApp.API.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711184226_AddSharedEventPaymentAllocationTouchedTransaction")]
    partial class AddSharedEventPaymentAllocationTouchedTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Account_AssetType", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "AssetTypeId");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Account_AssetTypes");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.AssetQuote", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("AssetId", "Date", "Type");

                    b.ToTable("AssetQuotes");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.AssetSplitEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SplitRatio")
                        .HasColumnType("decimal(18,10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetSplitEvents");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3992),
                            Environment = "FIAT",
                            Name = "Moneda",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3994)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3997),
                            Environment = "CRYPTO",
                            Name = "Criptomoneda",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3997)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3998),
                            Environment = "BOLSA",
                            Name = "Accion Argentina",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3998)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3999),
                            Environment = "BOLSA",
                            Name = "CEDEAR",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(3999)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4000),
                            Environment = "BOLSA",
                            Name = "FCI",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4000)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4001),
                            Environment = "BOLSA",
                            Name = "Bono",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4001)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4002),
                            Environment = "BOLSA",
                            Name = "Accion USA",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4002)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4003),
                            Environment = "BOLSA",
                            Name = "Obligacion Negociable",
                            UpdatedAt = new DateTime(2026, 7, 11, 18, 42, 25, 497, DateTimeKind.Utc).AddTicks(4003)
                        });
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Asset_User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<bool>("isMainReference")
                        .HasColumnType("bit");

                    b.Property<bool>("isReference")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("Assets_Users");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.BondPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmortizationPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("BondPayments");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardPayment", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("CardId", "Date");

                    b.ToTable("CardPayments");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstInstallment")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastInstallment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Repeat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionClassId")
                        .HasColumnType("int");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CardId");

                    b.HasIndex("TransactionClassId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardTransactionDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardTransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CardTransactionDiscounts");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardTransactionDiscountInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardTransactionDiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardTransactionDiscountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("CardTransactionDiscountInstallments");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.InvestmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommerceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpenseTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("IncomeTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTransactionId");

                    b.HasIndex("IncomeTransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("InvestmentTransactions");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SharedEvents");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PayerPersonId")
                        .HasColumnType("int");

                    b.Property<int>("SharedEventId")
                        .HasColumnType("int");

                    b.Property<int?>("SharedExpenseId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionClassId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CardTransactionId");

                    b.HasIndex("PayerPersonId");

                    b.HasIndex("SharedEventId");

                    b.HasIndex("SharedExpenseId");

                    b.HasIndex("TransactionClassId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedEventMovements");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventMovementShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountSettled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SharedEventMovementId")
                        .HasColumnType("int");

                    b.Property<int?>("SharedExpenseSplitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SharedEventMovementId");

                    b.HasIndex("SharedExpenseSplitId");

                    b.ToTable("SharedEventMovementShares");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SharedEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SharedEventId", "PersonId")
                        .IsUnique();

                    b.ToTable("SharedEventParticipants");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternalCompensation")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SharedEventId")
                        .HasColumnType("int");

                    b.Property<int?>("ToPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("FromPersonId");

                    b.HasIndex("SharedEventId");

                    b.HasIndex("ToPersonId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedEventPayments");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventPaymentAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedExchangeInTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedExchangeOutTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedExpenseTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedIncomeTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("SharedEventMovementShareId")
                        .HasColumnType("int");

                    b.Property<int>("SharedEventPaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("SharedExpenseSplitId")
                        .HasColumnType("int");

                    b.Property<int?>("TouchedTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedExchangeInTransactionId");

                    b.HasIndex("CreatedExchangeOutTransactionId");

                    b.HasIndex("CreatedExpenseTransactionId");

                    b.HasIndex("CreatedIncomeTransactionId");

                    b.HasIndex("SharedEventMovementShareId");

                    b.HasIndex("SharedEventPaymentId");

                    b.HasIndex("SharedExpenseSplitId");

                    b.HasIndex("TouchedTransactionId");

                    b.ToTable("SharedEventPaymentAllocations");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardTransactionId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedExpenses");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpenseReimbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SharedExpenseSplitId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SharedExpenseSplitId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SharedExpenseReimbursements");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpenseSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountReimbursed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InstallmentSplitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SharedExpenseId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SharedExpenseId");

                    b.ToTable("SharedExpenseSplits");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuotePrice")
                        .HasColumnType("decimal(18,10)");

                    b.Property<int?>("TransactionClassId")
                        .HasColumnType("int");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CardTransactionId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TransactionClassId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.TransactionClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncExp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionClasses");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.TripSuggestionDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardTransactionId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("TripSuggestionDismissals");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JazFinanzasApp.API.Infrastructure.Data.QueryResults.CryptoStatsByDateCommerceResult", b =>
                {
                    b.Property<string>("CommerceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("CryptoStatsByDateCommerceResult");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Infrastructure.Data.QueryResults.CryptoStatsByDateResult", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("CryptoStatsByDateResult");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Infrastructure.Data.QueryResults.StockStatsListResult", b =>
                {
                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("StockStatsListResult");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Infrastructure.Data.QueryResults.StocksGralStatsResult", b =>
                {
                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalValue")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("StocksGralStatsResult");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Infrastructure.Data.QueryResults.TotalBalanceResult", b =>
                {
                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("TotalBalanceResult");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Account", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Account_AssetType", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Account", "Account")
                        .WithMany("Account_AssetTypes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Asset", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.AssetQuote", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.AssetSplitEvent", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Asset_User", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.BondPayment", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Card", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardPayment", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardTransaction", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.TransactionClass", "TransactionClass")
                        .WithMany()
                        .HasForeignKey("TransactionClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Card");

                    b.Navigation("TransactionClass");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardTransactionDiscount", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.CardTransaction", "CardTransaction")
                        .WithMany()
                        .HasForeignKey("CardTransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.CardTransactionDiscountInstallment", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.CardTransactionDiscount", "CardTransactionDiscount")
                        .WithMany()
                        .HasForeignKey("CardTransactionDiscountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardTransactionDiscount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.InvestmentTransaction", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "ExpenseTransaction")
                        .WithMany()
                        .HasForeignKey("ExpenseTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "IncomeTransaction")
                        .WithMany()
                        .HasForeignKey("IncomeTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseTransaction");

                    b.Navigation("IncomeTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Person", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Portfolio", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEvent", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventMovement", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.CardTransaction", "CardTransaction")
                        .WithMany()
                        .HasForeignKey("CardTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Person", "PayerPerson")
                        .WithMany()
                        .HasForeignKey("PayerPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.SharedEvent", "SharedEvent")
                        .WithMany("Movements")
                        .HasForeignKey("SharedEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.SharedExpense", "SharedExpense")
                        .WithMany()
                        .HasForeignKey("SharedExpenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.TransactionClass", "TransactionClass")
                        .WithMany()
                        .HasForeignKey("TransactionClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CardTransaction");

                    b.Navigation("PayerPerson");

                    b.Navigation("SharedEvent");

                    b.Navigation("SharedExpense");

                    b.Navigation("Transaction");

                    b.Navigation("TransactionClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventMovementShare", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.SharedEventMovement", "SharedEventMovement")
                        .WithMany("Shares")
                        .HasForeignKey("SharedEventMovementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.SharedExpenseSplit", "SharedExpenseSplit")
                        .WithMany()
                        .HasForeignKey("SharedExpenseSplitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Person");

                    b.Navigation("SharedEventMovement");

                    b.Navigation("SharedExpenseSplit");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventParticipant", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.SharedEvent", "SharedEvent")
                        .WithMany("Participants")
                        .HasForeignKey("SharedEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("SharedEvent");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventPayment", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Person", "FromPerson")
                        .WithMany()
                        .HasForeignKey("FromPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.SharedEvent", "SharedEvent")
                        .WithMany("Payments")
                        .HasForeignKey("SharedEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Person", "ToPerson")
                        .WithMany()
                        .HasForeignKey("ToPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("FromPerson");

                    b.Navigation("SharedEvent");

                    b.Navigation("ToPerson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventPaymentAllocation", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "CreatedExchangeInTransaction")
                        .WithMany()
                        .HasForeignKey("CreatedExchangeInTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "CreatedExchangeOutTransaction")
                        .WithMany()
                        .HasForeignKey("CreatedExchangeOutTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "CreatedExpenseTransaction")
                        .WithMany()
                        .HasForeignKey("CreatedExpenseTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "CreatedIncomeTransaction")
                        .WithMany()
                        .HasForeignKey("CreatedIncomeTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.SharedEventMovementShare", "SharedEventMovementShare")
                        .WithMany()
                        .HasForeignKey("SharedEventMovementShareId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.SharedEventPayment", "SharedEventPayment")
                        .WithMany("Allocations")
                        .HasForeignKey("SharedEventPaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.SharedExpenseSplit", "SharedExpenseSplit")
                        .WithMany()
                        .HasForeignKey("SharedExpenseSplitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "TouchedTransaction")
                        .WithMany()
                        .HasForeignKey("TouchedTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedExchangeInTransaction");

                    b.Navigation("CreatedExchangeOutTransaction");

                    b.Navigation("CreatedExpenseTransaction");

                    b.Navigation("CreatedIncomeTransaction");

                    b.Navigation("SharedEventMovementShare");

                    b.Navigation("SharedEventPayment");

                    b.Navigation("SharedExpenseSplit");

                    b.Navigation("TouchedTransaction");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpense", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.CardTransaction", "CardTransaction")
                        .WithMany()
                        .HasForeignKey("CardTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardTransaction");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpenseReimbursement", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.SharedExpenseSplit", "SharedExpenseSplit")
                        .WithMany()
                        .HasForeignKey("SharedExpenseSplitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SharedExpenseSplit");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpenseSplit", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.SharedExpense", "SharedExpense")
                        .WithMany("Splits")
                        .HasForeignKey("SharedExpenseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("SharedExpense");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Transaction", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.CardTransaction", "CardTransaction")
                        .WithMany()
                        .HasForeignKey("CardTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JazFinanzasApp.API.Domain.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.TransactionClass", "TransactionClass")
                        .WithMany()
                        .HasForeignKey("TransactionClassId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("CardTransaction");

                    b.Navigation("Portfolio");

                    b.Navigation("TransactionClass");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.TransactionClass", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Trip", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.TripSuggestionDismissal", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.CardTransaction", "CardTransaction")
                        .WithMany()
                        .HasForeignKey("CardTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JazFinanzasApp.API.Domain.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardTransaction");

                    b.Navigation("Transaction");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JazFinanzasApp.API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("JazFinanzasApp.API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.Account", b =>
                {
                    b.Navigation("Account_AssetTypes");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEvent", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Participants");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventMovement", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedEventPayment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("JazFinanzasApp.API.Domain.SharedExpense", b =>
                {
                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
